<a href="https://colab.research.google.com/github/faizz10/datascience/blob/main/p5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np

A = np.array([[2, 1, -2],[3, 0, 1],[1, 1, -1]])
b = np.array([-3, 5, -2])
x = np.linalg.solve(A, b)
print("Matrix A:")
print(A)

print("Vector b:")
print(b)

print("Solution for x:")
print(x)

Matrix A:
[[ 2  1 -2]
 [ 3  0  1]
 [ 1  1 -1]]
Vector b:
[-3  5 -2]
Solution for x:
[ 1. -1.  2.]
